---
functional:
 #RC1
  - Должна быть реализована авторизация пользователя в приложении
 #RC2
  - У авторизованного пользователя должна быть возможность создать новую игру
 #RC3
  - Система должна поддерживать отложенную инициализацию языка. Язык не должен быть привязан к созданию сессии
 #RC4
  - Каждый игрок должен иметь возможность выбрать любой язык программирования из списка доступных языков
 #RC5
  - Должен быть реализован режим ожидания второго игрока
 #RC6
  - Должен быть список игр, доступных для подключения, в котором выводятся созданные игры
 #RC7
  - Второй игрок подключается к выбранной игре по нажатию кнопки "Connect to game"
 #RC8
  - Оба игрока находятся в одном игровом пространстве
 #RC9
  - В игровом пространстве должны находиться два редактора кода (слева - свой, справа - соперника)
 #RC10
  -  Игра проходит в реальном времени, должен быть виден набираемый противником текст
 #RC11
  - Количество попыток проверки кода неограничивается (нажатие кнопки "Run")
 #RC12
  - Состояние сессии должно восстанавливаться после разрыва соединения и переподключения
 #RC13
  - Игровое время неограничивается, игра длится до найденного победного решения или до момента, когда один игрок сдался
 #RC14
  - Должна быть возможность выбрать соперником бота
 #RC15
non-functional:
 #RC16 
  - Приложение должно быть разработано с учетом удобства использования 
 #RC17
  - Приложение должно работать на мобильных устройствах с учётом удобства использования
 #RC18
  - Приложение должно быть оптимизировано для скорости работы
 #RC19
  - Сайт должен быть способен обрабатывать большое количество трафика (100 одновременных пользователей)
 #RC20
  - Сайт должен быть безопасным и защищать данные пользователя
 #RC21 
  - Сайт должен быть совместимым с последними версиями браузеров
implicit:
  



 